server:
 port: 9999
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
   preferIpAddress: true
spring:
 application:
  name: api-gateway
 cloud:
  gateway:
   routes:
    - id: appointment-service
      predicates:
       - Path=/appointment-service/**
      uri: http://localhost:10001
    - id: file-storage
      predicates:
        - Path=/file-storage/**
      uri: http://localhost:10003
   globalcors:
    cors-configurations:
     '[/**]':
      allowedOrigins: "http://localhost:10010"
      allowedHeaders: "*"
      allowedMethods: "*"
   discovery:
    locator:
     enabled: true
   httpclient:
     connect-timeout: 60000
     response-timeout: 60s
application:
 security:
  jwt:
   secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
springdoc:
 api-docs:
  enabled: true
  path: /v3/api-docs
 swagger-ui:
  enabled: true
  config-url: /v3/api-docs/swagger-config
  urls:
   -   name: gateway-service
       url: /v3/api-docs
   -  name: auth-service
      url: /auth-service/v3/api-docs
   - name: file-storage
     url: /file-storage/v3/api-docs
