server:
 port: 9999
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
   preferIpAddress: true
spring:
 application:
  name: api-gateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   httpclient:
     connect-timeout: 60000
     response-timeout: 60s
application:
 security:
  jwt:
   secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970