app:
  name: payment-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_schema: info
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/appointmentHospital
    username: user
    password: passpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      user-service: userTopic

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 10006
springdoc:
  api-docs:
    enabled: true
    path: /payment-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /payment-service/swagger-ui.html
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: http://localhost:10006/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other