app:
  name: appointment-service
spring:
  application:
    name: appointment-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/appointment
    username: user
    password: passpass
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 10002