app:
  name: appointment-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: appointment-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_schema: account
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3307/appointmentHospital
      username: user
      password: passpass
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: robotmailer1010@gmail.com
    password: bgoz edtg nnyw wcua
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    password:
      default-prefix: 123456
server:
  port: 10001
#openapi:
#  service:
#    title: auth-service doc
#    version: 1.0.0
#    url: http://localhost:9999 #api gateway url
#springdoc:
#  api-docs:
#    path: /auth-service/v3/api-docs
#  swagger-ui:
#    path: /auth-service/swagger-ui.html
springdoc:
  api-docs:
    enabled: true
    path: /auth-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth-service/swagger-ui.html
twilio:
  account-sid:
  auth-token:
  trial-number:
scheduleService:
  firstStart: 07:30
  firstEnd : 11:30
  lastStart : 13:00
  lastEnd : 17:00
  bigStepGap : 30
  stepGap : 7
speedSms:
  access-token: DGbph-1O7DjsmdX5jyFtytIm1sKAwXyd
  sender: 84386152395